[package]
name = "lasttalon/linked-list"
version = "0.1.0"
description = "A linked list implementation."
license = "MIT"
authors = ["Lucas Gangstad <lucas@lasttalon.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.lua", "*.dev.lua", "tests", "docs"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
